app_qoutes/app_qoutes/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

app_qoutes/quotes/urls.py
from django.urls import path
from quotes import views
from quotes.views import QuoteAdd, AuthorAdd


app_name = "quotes"

urlpatterns = [
    path("", views.all_quotes, name="all-quotes"),
    path("add-quote/", QuoteAdd.as_view(), name="add-quote"),
    path("add-author/", AuthorAdd.as_view(), name="add-author"),
    path("author/<str:author_name>", views.about_author, name="about-author"),
]

app_qoutes/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView,PasswordResetDoneView,PasswordResetConfirmView,PasswordResetCompleteView

from users import views
from users.forms import LoginForm

app_name = "users"

urlpatterns = [
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(template_name = "users/login.html", form_class = LoginForm,redirect_authenticated_user=True), name="login"),
    path("logout/", LogoutView.as_view(template_name = "users/logout.html"), name="logout"),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html', success_url='/users/reset-password/complete/'), name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

app_qoutes/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(unique=True, null=False)
    born_date = models.CharField(max_length=50, null=False)
    born_location = models.CharField(max_length=50, null=False)
    description = models.TextField(null=False)

    def __str__(self):
        return self.fullname


class Quote(models.Model):
    quote = models.CharField(max_length=255, null=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    tags = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.quote

app_qoutes/users/models.py
from django.db import models

# Create your models here.

app_qoutes/quotes/forms.py
from django.forms import ModelForm, CharField
from quotes.models import Quote, Author


class QuoteForm(ModelForm):
    author = CharField(max_length=200)

    class Meta:
        model = Quote
        fields = ["quote", "tags"]

    def clean_author(self):
        author_name = self.cleaned_data["author"]
        author, _ = Author.objects.get_or_create(fullname=author_name)
        return author


class AuthorForm(ModelForm):
    fullname = CharField(required=True)
    born_date = CharField(max_length=50, min_length=20, required=True)
    born_location = CharField(max_length=50, min_length=20, required=True)
    description = CharField(required=True)

    class Meta:
        model = Author
        fields = ("fullname", "born_date", "born_location", "description")

app_qoutes/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailField,EmailInput,PasswordInput

class RegisterForm(UserCreationForm):
    username = CharField(max_length=20, min_length=5, required=True, widget=TextInput(attrs={"class":"form-control"}))
    email = EmailField(max_length=25, required=True, widget=EmailInput(attrs={"class":"form-control"}))
    password1 = CharField(required=True, widget=PasswordInput(attrs={"class":"form-control"}))
    password2 = CharField(required=True, widget=PasswordInput(attrs={"class":"form-control"}))

    class Meta:
        model = User
        fields = ('username','email','password1','password2')

class LoginForm(AuthenticationForm):
    username = CharField(max_length=20, min_length=5, required=True, widget=TextInput(attrs={"class":"form-control"}))
    password = CharField(required=True, widget=PasswordInput(attrs={"class":"form-control"}))

    class Meta:
        model = User
        fields = ('username','password')

app_qoutes/quotes/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.views import View
from .forms import QuoteForm, AuthorForm
from .models import Quote, Author


def all_quotes(request):
    data = Quote.objects.all()
    per_page = 10
    paginator = Paginator(data, per_page)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "quotes/all-quotes.html", {"page_obj": page_obj})


def about_author(request, author_name: str):
    author = get_object_or_404(Author, fullname=author_name)
    return render(request, "quotes/about-author.html", context={"author": author})


# def all_quotes(request):
#     quotes = Quote.objects.all()
#     return render(request, "quotes/all-quotes.html", context={"quotes": quotes})


class QuoteAdd(View):
    template_name = "quotes/add-quote.html"

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {"form": QuoteForm()})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote = form.save(commit=False)
            author_name = form.cleaned_data["author"]
            author, _ = Author.objects.get_or_create(fullname=author_name)
            quote.author = author
            quote.save()
            return redirect(to="quotes:all-quotes")
        else:
            return render(request, self.template_name, {"form": form})


class AuthorAdd(View):
    template_name = "quotes/add-author.html"

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {"form": AuthorForm()})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:all-quotes")
        else:
            return render(request, self.template_name, {"form": form})

app_qoutes/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from users.forms import RegisterForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import PasswordResetView
from django.urls import reverse_lazy

class RegisterView(View):
    template_name = "users/register.html"
    form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="quotes:all-quotes")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            username = form.save()
            username = form.cleaned_data["username"]
            messages.success(
                request,
                f"Congratulations, {username}! You have successfully registered",
            )
            return redirect(to="users:login")
        return render(request, self.template_name, {"form": form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "users/password_reset.html"
    email_template_name = "users/password_reset_email.html"
    html_email_template_name = "users/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    success_message = (
        "An email with instructions to reset your password has been sent to email."
    )
    subject_template_name = "users/password_reset_subject.txt"

app_qoutes/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  
    {% block style %} {% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <title>Mizhik-App</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a
              class="nav-link active"
              aria-current="page"
              href="{% url 'quotes:all-quotes'%}"
              >Quotes</a
            >
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'quotes:add-quote' %}">Add qoutes</a>
            <a class="nav-link" href="{% url 'quotes:add-author' %}">Add author</a>
          </div>
        </div>
        <div class="navbar">
          <form action="{% url 'users:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Logout</button>
          </form>
          {% else %}
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          <a class="nav-link" href="{% url 'users:login' %}">Login</a>
          {% endif %}
        </div>
      </div>
    </nav>
    {% block body %} {% endblock %}
  </body>
</html>

app_qoutes/templates/quotes/about-author.html
{% extends 'base.html' %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'quotes/main.css' %}" />
{% endblock %}
{% block body %}
<div class="author-details">
  <h3 class="author-title">{{ author.fullname }}</h3>
  <p>
    <strong>Born:</strong>
    <span class="author-born-date">{{ author.born_date }}</span>
    <span class="author-born-location">{{ author.born_location }}</span>
  </p>
  <p><strong>Description:</strong></p>
  <div class="author-description">{{ author.description }}</div>
</div>
{% endblock %}

app_qoutes/templates/quotes/add-author.html
{% extends 'base.html' %} {% block style %} {% load static %}
<link rel="stylesheet" href="{% static 'quotes/main.css' %}" />
{% endblock %} {% block body %}

<div class="quotes">
  <form method="post">
    {% csrf_token %} {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {{ form.non_field_errors }}
    </div>
    {% endif %}

    <div class="mb-3">
      <label for="id_quote" class="form-label">Fullname</label>
      {{ form.fullname }} {% if form.quote.errors %}
      <div class="alert alert-danger" role="alert">{{ form.quote.errors }}</div>
      {% endif %}
    </div>

    <div class="mb-3">
      <label for="id_author" class="form-label">Born Date</label>
      {{ form.born_date }} {% if form.author.errors %}
      <div class="alert alert-danger" role="alert">
        {{ form.author.errors }}
      </div>
      {% endif %}
    </div>

    <div class="mb-3">
      <label for="id_tags" class="form-label">Born Location</label>
      {{ form.born_location }} {% if form.tags.errors %}
      <div class="alert alert-danger" role="alert">{{ form.tags.errors }}</div>
      {% endif %}
    </div>

    <div class="mb-3">
      <label for="id_tags" class="form-label">Description</label>
      {{ form.description }} {% if form.tags.errors %}
      <div class="alert alert-danger" role="alert">{{ form.tags.errors }}</div>
      {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset" class="btn btn-secondary">Reset</button>
  </form>
</div>

{% endblock %}

app_qoutes/templates/quotes/add-quote.html
{% extends 'base.html' %} {% block style %} {% load static %}
<link rel="stylesheet" href="{% static 'quotes/main.css' %}" />
{% endblock %} {% block body %}
<div class="container">
  <form method="post">
    {% csrf_token %} {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {{ form.non_field_errors }}
    </div>
    {% endif %}

    <div class="mb-3">
      <label for="id_quote" class="form-label">Quote</label>
      {{ form.quote }} {% if form.quote.errors %}
      <div class="alert alert-danger" role="alert">{{ form.quote.errors }}</div>
      {% endif %}
    </div>

    <div class="mb-3">
      <label for="id_author_name" class="form-label">Author</label>
      {{ form.author }} {% if form.author.errors %}
      <div class="alert alert-danger" role="alert">
        {{ form.author.errors }}
      </div>
      {% endif %}
    </div>

    <div class="mb-3">
      <label for="id_tags" class="form-label">Tags</label>
      {{ form.tags }} {% if form.tags.errors %}
      <div class="alert alert-danger" role="alert">{{ form.tags.errors }}</div>
      {% endif %}
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    <button type="reset" class="btn btn-secondary">Reset</button>
  </form>
</div>
{% endblock %}

app_qoutes/templates/quotes/all-quotes.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block style%} 
  {% load static %}
  <link rel="stylesheet" href="{% static 'quotes/main.css' %}" />
{% endblock %} 

{% block body%}
  {% for quote in page_obj %}
    <div class="quote-box">
      <div class="quote">
        <div class="text-quotes">
          <div class="text-quote">"{{quote.quote}}"</div>
        </div>
        <div>
          by <span class="author">{{ quote.author.fullname }}</span>
          <a
            href="{% url 'quotes:about-author' quote.author.fullname %}"
            class="about"
            >(about)</a
          >
        </div>

        <div class="tags">
          <span>Tags:</span>
          {% for q in quote.tags|split_comma %}
            <div class="tag">{{ q }}</div>
          {% endfor %}
        </div>
      </div>
    </div>
  {% endfor %}

  <!-- Добавление пагинации -->
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
{% endblock %}

app_qoutes/templates/users/login.html
{% extends 'base.html' %}

{% block body %}
<div class="container mt-3">
    <h2>Login User</h2>

    {% if messages %} 
    <div class="messages">
        {% for message in messages %}
        <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password }}
            </label>
            <span>{{form.errors.password}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
        <div class="small text-center">
            <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
        </div>
    </form>
</form>
</div>
{% endblock %}

app_qoutes/templates/users/logout.html
{% extends 'base.html' %}

{% block style %}

{% load static %}
<link rel="stylesheet" href="{% static 'users/main.css' %}" />
{% endblock %}

{% block body %}

    <div class="goodbay">
        <h1>Come back!</h1>
    </div>

{% endblock %}

app_qoutes/templates/users/password_reset.html
{% extends "base.html" %}
{% block body %}
<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

app_qoutes/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block body %}

    <h2>Password reset complete!</h2>

{% endblock %}

app_qoutes/templates/users/password_reset_confirm.html
{% extends "base.html" %} 
{% block body %}

<h2>Enter new password</h2>
<form method="post">
  {% csrf_token %} 
  {{ form.as_p }}
  <button type="submit">Save new password</button>
</form>

{% endblock %}

app_qoutes/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block body %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

app_qoutes/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

app_qoutes/templates/users/register.html
{% extends 'base.html' %}

{% block body %}
<div class="container mt-3">
    <h2>Register User</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Email
                {{ form.email }}
            </label>
            <span>{{form.errors.email}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password1 }}
            </label>
            <span>{{form.errors.password1}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Repeat Password
                {{ form.password2 }}
            </label>
            <span>{{form.errors.password2}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}